name: allj
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - xarray
  - netcdf4
  - h5netcdf
  - matplotlib
  - cartopy
  - scipy
  - pandas
  - statsmodels
  - requests
  - pip:
    - cdsapi
